name: ads_bi_class_study_stats_wide_df
title: Ads Bi Class Study Stats Wide Df
description: 每日整体学情概览应用表
table: ads_bi_class_study_stats_wide_df
source_id: 1
source_database: df_cb_258187
data_source: maxcompute
status: draft
partition:
  field: ds
  type: date
  format: yyyyMMdd
  max_range_days: 90
default_filters: []
dimensions:
  class_name:
    title: 班级名称
    type: string
    sql: '{CUBE}.class_name'
    description: 班级名称
    source_data_type: string
    primary_key: false
  ds:
    title: 分区日期
    type: time
    sql: '{CUBE}.ds'
    description: 分区日期
    source_data_type: string
    primary_key: false
  grade_name:
    title: 年级名称
    type: string
    sql: '{CUBE}.grade_name'
    description: 年级名称
    source_data_type: string
    primary_key: false
  school_name:
    title: 学校名称
    type: string
    sql: '{CUBE}.school_name'
    description: 学校名称
    source_data_type: string
    primary_key: false
  subject_name:
    title: 科目名称
    type: string
    sql: '{CUBE}.subject_name'
    description: 科目名称
    source_data_type: string
    primary_key: false
measures:
  total_count:
    title: 总数
    type: count
    sql: '{CUBE}.subject_name'
    description: 自动生成的记录总数指标
    source_data_type: count
    certified: true
    non_additive: false
  sum_active_student_cnt:
    title: 活跃学生数
    type: sum
    sql: '{CUBE}.active_student_cnt'
    description: 自动生成的 active_student_cnt sum指标
    source_data_type: bigint
    certified: false
    non_additive: false
    synonyms: []
    tags: []
  sum_ai_scoring_cnt:
    title: AI批改次数
    type: sum
    sql: '{CUBE}.ai_scoring_cnt'
    description: 自动生成的 ai_scoring_cnt sum指标
    source_data_type: bigint
    certified: false
    non_additive: false
    synonyms: []
    tags: []
  sum_ai_session_cnt:
    title: AI课会话数
    type: sum
    sql: '{CUBE}.ai_session_cnt'
    description: 自动生成的 ai_session_cnt sum指标
    source_data_type: bigint
    certified: false
    non_additive: false
    synonyms: []
    tags: []
  sum_answer_cnt:
    title: 答题次数
    type: sum
    sql: '{CUBE}.answer_cnt'
    description: 自动生成的 answer_cnt sum指标
    source_data_type: bigint
    certified: false
    non_additive: false
    synonyms: []
    tags: []
  sum_answer_duration:
    title: 总答题时长
    type: sum
    sql: '{CUBE}.answer_duration'
    description: 自动生成的 answer_duration sum指标
    source_data_type: bigint
    certified: false
    non_additive: false
    synonyms: []
    tags: []
  sum_consolidate_session_cnt:
    title: 巩固练习会话数
    type: sum
    sql: '{CUBE}.consolidate_session_cnt'
    description: 自动生成的 consolidate_session_cnt sum指标
    source_data_type: bigint
    certified: false
    non_additive: false
    synonyms: []
    tags: []
  sum_correct_answer_cnt:
    title: 正确答题次数
    type: sum
    sql: '{CUBE}.correct_answer_cnt'
    description: 自动生成的 correct_answer_cnt sum指标
    source_data_type: bigint
    certified: false
    non_additive: false
    synonyms: []
    tags: []
  sum_extend_session_cnt:
    title: 扩展练习会话数
    type: sum
    sql: '{CUBE}.extend_session_cnt'
    description: 自动生成的 extend_session_cnt sum指标
    source_data_type: bigint
    certified: false
    non_additive: false
    synonyms: []
    tags: []
  sum_lesson_cnt:
    title: 课程数量
    type: sum
    sql: '{CUBE}.lesson_cnt'
    description: 自动生成的 lesson_cnt sum指标
    source_data_type: bigint
    certified: false
    non_additive: false
    synonyms: []
    tags: []
  sum_session_cnt:
    title: 会话总数
    type: sum
    sql: '{CUBE}.session_cnt'
    description: 自动生成的 session_cnt sum指标
    source_data_type: bigint
    certified: false
    non_additive: false
    synonyms: []
    tags: []
  sum_study_duration:
    title: 总学习时长
    type: sum
    sql: '{CUBE}.study_duration'
    description: 自动生成的 study_duration sum指标
    source_data_type: bigint
    certified: false
    non_additive: false
    synonyms: []
    tags: []
  sum_subjective_answer_cnt:
    title: 主观题答题次数
    type: sum
    sql: '{CUBE}.subjective_answer_cnt'
    description: 自动生成的 subjective_answer_cnt sum指标
    source_data_type: bigint
    certified: false
    non_additive: false
    synonyms: []
    tags: []
  sum_total_student_cnt:
    title: 总学生数
    type: sum
    sql: '{CUBE}.total_student_cnt'
    description: 自动生成的 total_student_cnt sum指标
    source_data_type: bigint
    certified: false
    non_additive: false
    synonyms: []
    tags: []
  sum_video_duration:
    title: 总视频时长
    type: sum
    sql: '{CUBE}.video_duration'
    description: 自动生成的 video_duration sum指标
    source_data_type: bigint
    certified: false
    non_additive: false
    synonyms: []
    tags: []
segments: {}
joins: {}
