name: dws_study_student_answer_kb_history_df_question_type
title: 题目类型ID
object_name: dws_study_student_answer_kb_history_df
property_type: string
description: 来自字段候选集 fcand_d645fef174a96d13，角色 dimension.categorical
aliases:
- question_type
status: active
