name: student_comment_report_updated_at
title: 举报记录更新时间，来源于源表update_time
object_name: student_comment
property_type: time
description: 举报记录更新时间，来源于源表update_time
aliases:
- report_updated_at
status: active
