"""initial production schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-05-18

生产首次上线基线：从空库创建当前完整 schema。
旧开发阶段 revision 已在上线前 squash，不作为生产迁移历史。
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

from app.shared import db_types


revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_data_policies',
    sa.Column('policy_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('subject_roles', db_types.JsonType(), nullable=False),
    sa.Column('resource_scope', db_types.JsonType(), nullable=False),
    sa.Column('actions', db_types.JsonType(), nullable=False),
    sa.Column('effect', sa.String(length=32), server_default='allow', nullable=False),
    sa.Column('execution_profile_code', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('policy_version', sa.String(length=64), server_default='v1', nullable=False),
    sa.Column('policy_epoch', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_by', sa.String(length=191), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('policy_code')
    )
    op.create_index('idx_access_data_policies_priority', 'access_data_policies', ['priority'], unique=False)
    op.create_index('idx_access_data_policies_status', 'access_data_policies', ['status'], unique=False)
    op.create_index('ix_access_data_policies_execution_profile_code', 'access_data_policies', ['execution_profile_code'], unique=False)
    op.create_table('access_delegation_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('actor_principal_id', sa.String(length=191), nullable=False),
    sa.Column('delegated_principal_id', sa.String(length=191), nullable=True),
    sa.Column('tenant_key', sa.String(length=128), nullable=True),
    sa.Column('message_id', sa.String(length=191), nullable=True),
    sa.Column('chat_id', sa.String(length=191), nullable=True),
    sa.Column('event_id', sa.String(length=191), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_access_delegation_events_actor', 'access_delegation_events', ['actor_principal_id'], unique=False)
    op.create_index('idx_access_delegation_events_created', 'access_delegation_events', ['created_at'], unique=False)
    op.create_index('idx_access_delegation_events_delegated', 'access_delegation_events', ['delegated_principal_id'], unique=False)
    op.create_index('idx_access_delegation_events_message', 'access_delegation_events', ['message_id'], unique=False)
    op.create_table('access_execution_profiles',
    sa.Column('profile_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('credential_mode', sa.String(length=32), nullable=False),
    sa.Column('credential_ref', sa.String(length=255), nullable=True),
    sa.Column('data_level', sa.String(length=16), server_default='M1', nullable=False),
    sa.Column('allowed_operations', db_types.JsonType(), nullable=False),
    sa.Column('max_rows', sa.Integer(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('export_allowed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('requires_strong_audit', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('created_by', sa.String(length=191), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('profile_code')
    )
    op.create_index('idx_access_execution_profiles_level', 'access_execution_profiles', ['data_level'], unique=False)
    op.create_index('idx_access_execution_profiles_status', 'access_execution_profiles', ['status'], unique=False)
    op.create_table('access_policy_decisions',
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('principal_id', sa.String(length=191), nullable=False),
    sa.Column('actor_id', sa.String(length=191), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('data_level', sa.String(length=16), nullable=False),
    sa.Column('resource_set', db_types.JsonType(), nullable=False),
    sa.Column('sql_hashes', db_types.JsonType(), nullable=False),
    sa.Column('matched_policies', db_types.JsonType(), nullable=False),
    sa.Column('execution_profile_code', sa.String(length=64), nullable=True),
    sa.Column('policy_version', sa.String(length=64), nullable=True),
    sa.Column('policy_epoch', sa.Integer(), server_default='1', nullable=False),
    sa.Column('decision_type', sa.String(length=32), server_default='inline', nullable=False),
    sa.Column('governance_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_index('idx_access_policy_decisions_created', 'access_policy_decisions', ['created_at'], unique=False)
    op.create_index('idx_access_policy_decisions_decision', 'access_policy_decisions', ['decision'], unique=False)
    op.create_index('idx_access_policy_decisions_level', 'access_policy_decisions', ['data_level'], unique=False)
    op.create_index('idx_access_policy_decisions_principal', 'access_policy_decisions', ['principal_id'], unique=False)
    op.create_table('access_principals',
    sa.Column('principal_id', sa.String(length=191), nullable=False),
    sa.Column('principal_type', sa.String(length=32), nullable=False),
    sa.Column('idp', sa.String(length=32), nullable=False),
    sa.Column('tenant_key', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('employee_no', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('raw_profile', db_types.JsonType(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('principal_id')
    )
    op.create_index('idx_access_principals_status', 'access_principals', ['status'], unique=False)
    op.create_index('idx_access_principals_tenant', 'access_principals', ['tenant_key'], unique=False)
    op.create_index('idx_access_principals_type', 'access_principals', ['principal_type'], unique=False)
    op.create_table('access_role_bindings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_key', sa.String(length=255), nullable=False),
    sa.Column('role_code', sa.String(length=64), nullable=False),
    sa.Column('role_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), server_default='manual', nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('created_by', sa.String(length=191), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_type', 'subject_key', 'role_code', 'role_type', 'effective_from', name='uq_access_role_bindings_effective')
    )
    op.create_index('idx_access_role_bindings_role', 'access_role_bindings', ['role_type', 'role_code'], unique=False)
    op.create_index('idx_access_role_bindings_status', 'access_role_bindings', ['status'], unique=False)
    op.create_index('idx_access_role_bindings_subject', 'access_role_bindings', ['subject_type', 'subject_key'], unique=False)
    op.create_table('agent_query_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('app_instance_id', sa.BigInteger(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('channel_ref', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('agent_response', sa.Text(), nullable=True),
    sa.Column('sql_executed', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('llm_provider', sa.String(length=20), nullable=True),
    sa.Column('token_usage', db_types.JsonType(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config_schema', db_types.JsonType(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('channels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('channel_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', db_types.JsonType(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('connection_config', db_types.JsonType(), nullable=False),
    sa.Column('extra_config', db_types.JsonType(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('connection_status', sa.String(length=20), nullable=True),
    sa.Column('last_test_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('datasource_table_cache',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('datasource_id', sa.BigInteger(), nullable=False),
    sa.Column('database_name', sa.String(length=200), nullable=False),
    sa.Column('table_list', db_types.JsonType(), nullable=False),
    sa.Column('table_count', sa.Integer(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_access_at', sa.DateTime(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('datasource_id', 'database_name', name='uq_datasource_database')
    )
    op.create_index('idx_datasource_table_cache_datasource', 'datasource_table_cache', ['datasource_id'], unique=False)
    op.create_index('idx_datasource_table_cache_expires', 'datasource_table_cache', ['expires_at'], unique=False)
    op.create_table('domain_publish_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('domain_id', sa.String(length=128), nullable=False),
    sa.Column('domain_code', sa.String(length=128), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('published_by', sa.String(length=128), nullable=True),
    sa.Column('diff_summary', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('snapshot', db_types.JsonType(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_domain_pub_records_domain_id', 'domain_publish_records', ['domain_id'], unique=False)
    op.create_index('idx_domain_pub_records_published_at', 'domain_publish_records', ['published_at'], unique=False)
    op.create_table('feishu_chat_ref',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=128), nullable=False),
    sa.Column('chat_name', sa.String(length=256), nullable=True),
    sa.Column('added_via', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_table('governance_audit_traces',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_name', sa.String(length=255), nullable=False),
    sa.Column('principal_id', sa.String(length=128), nullable=True),
    sa.Column('semantic_plan_id', sa.String(length=128), nullable=True),
    sa.Column('sql_hash', sa.String(length=128), nullable=True),
    sa.Column('gateway_query_id', sa.String(length=128), nullable=True),
    sa.Column('maxcompute_task_id', sa.String(length=128), nullable=True),
    sa.Column('viewer_roles', db_types.ArrayOfString(), nullable=False),
    sa.Column('route_type', sa.String(length=64), nullable=False),
    sa.Column('execution_target', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=64), nullable=False),
    sa.Column('policy', db_types.JsonType(), nullable=True),
    sa.Column('policy_decision', db_types.JsonType(), nullable=False),
    sa.Column('traceability', db_types.JsonType(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governance_audit_traces_decision'), 'governance_audit_traces', ['decision'], unique=False)
    op.create_index(op.f('ix_governance_audit_traces_gateway_query_id'), 'governance_audit_traces', ['gateway_query_id'], unique=False)
    op.create_index(op.f('ix_governance_audit_traces_maxcompute_task_id'), 'governance_audit_traces', ['maxcompute_task_id'], unique=False)
    op.create_index(op.f('ix_governance_audit_traces_principal_id'), 'governance_audit_traces', ['principal_id'], unique=False)
    op.create_index(op.f('ix_governance_audit_traces_route_type'), 'governance_audit_traces', ['route_type'], unique=False)
    op.create_index(op.f('ix_governance_audit_traces_semantic_plan_id'), 'governance_audit_traces', ['semantic_plan_id'], unique=False)
    op.create_index(op.f('ix_governance_audit_traces_sql_hash'), 'governance_audit_traces', ['sql_hash'], unique=False)
    op.create_index(op.f('ix_governance_audit_traces_target_name'), 'governance_audit_traces', ['target_name'], unique=False)
    op.create_index(op.f('ix_governance_audit_traces_target_type'), 'governance_audit_traces', ['target_type'], unique=False)
    op.create_index(op.f('ix_governance_audit_traces_timestamp'), 'governance_audit_traces', ['timestamp'], unique=False)
    op.create_table('query_execution_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('principal_id', sa.String(length=128), nullable=False),
    sa.Column('route_type', sa.String(length=64), nullable=False),
    sa.Column('semantic_plan_id', sa.String(length=128), nullable=True),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('logical_sql', sa.Text(), nullable=False),
    sa.Column('validated_sql', sa.Text(), nullable=False),
    sa.Column('sql_hash', sa.String(length=128), nullable=False),
    sa.Column('resource_set_json', db_types.JsonType(), nullable=False),
    sa.Column('data_level', sa.String(length=32), nullable=False),
    sa.Column('ticket_snapshot_json', db_types.JsonType(), nullable=False),
    sa.Column('governance_snapshot_json', db_types.JsonType(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('engine_query_id', sa.String(length=128), nullable=True),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('principal_id', 'idempotency_key', name='uq_query_execution_jobs_principal_idempotency')
    )
    op.create_index('idx_query_execution_jobs_principal_created', 'query_execution_jobs', ['principal_id', 'created_at'], unique=False)
    op.create_index('idx_query_execution_jobs_sql_hash', 'query_execution_jobs', ['sql_hash'], unique=False)
    op.create_index('idx_query_execution_jobs_status_lease_created', 'query_execution_jobs', ['status', 'lease_expires_at', 'created_at'], unique=False)
    op.create_index(op.f('ix_query_execution_jobs_engine_query_id'), 'query_execution_jobs', ['engine_query_id'], unique=False)
    op.create_index(op.f('ix_query_execution_jobs_lease_expires_at'), 'query_execution_jobs', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_query_execution_jobs_semantic_plan_id'), 'query_execution_jobs', ['semantic_plan_id'], unique=False)
    op.create_index(op.f('ix_query_execution_jobs_status'), 'query_execution_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_query_execution_jobs_trace_id'), 'query_execution_jobs', ['trace_id'], unique=False)
    op.create_table('query_exports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('sql_query', sa.Text(), nullable=False),
    sa.Column('visual_spec', db_types.JsonType(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('file_storage', sa.String(length=16), nullable=True),
    sa.Column('file_object_key', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('job_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_query_exports_status_created', 'query_exports', ['status', 'created_at'], unique=False)
    op.create_index('idx_query_exports_status_expires', 'query_exports', ['status', 'expires_at'], unique=False)
    op.create_index('idx_query_exports_user_created', 'query_exports', ['user_id', 'created_at'], unique=False)
    op.create_table('query_folders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('folder_name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['query_folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_folders_created_by'), 'query_folders', ['created_by'], unique=False)
    op.create_index(op.f('ix_query_folders_parent_id'), 'query_folders', ['parent_id'], unique=False)
    op.create_table('query_templates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('template_name', sa.String(length=200), nullable=False),
    sa.Column('template_description', sa.Text(), nullable=True),
    sa.Column('sql_template', sa.Text(), nullable=False),
    sa.Column('parameters', db_types.JsonType(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('tags', db_types.JsonType(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_templates_category'), 'query_templates', ['category'], unique=False)
    op.create_table('scheduled_queries',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sql', sa.Text(), nullable=False),
    sa.Column('datasource_id', sa.BigInteger(), nullable=False),
    sa.Column('cron', sa.String(length=64), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=16), nullable=True),
    sa.Column('owner_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('semantic_diagnose_runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('input_kind', sa.String(length=32), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('parse_ok', sa.Boolean(), nullable=True),
    sa.Column('validate_ok', sa.Boolean(), nullable=True),
    sa.Column('sql_text', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_diagnose_runs_user_id'), 'semantic_diagnose_runs', ['user_id'], unique=False)
    op.create_table('semantic_modeling_agent_sessions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('principal_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('payload_json', db_types.JsonType(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_semantic_modeling_sessions_principal_updated', 'semantic_modeling_agent_sessions', ['principal_id', 'updated_at'], unique=False)
    op.create_index('idx_semantic_modeling_sessions_status_updated', 'semantic_modeling_agent_sessions', ['status', 'updated_at'], unique=False)
    op.create_table('semantic_modeling_proposals',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload_json', db_types.JsonType(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_semantic_modeling_proposals_status_updated', 'semantic_modeling_proposals', ['status', 'updated_at'], unique=False)
    op.create_table('semantic_assets',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('namespace', sa.String(length=64), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('asset_key', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_revision_id', sa.String(length=128), nullable=True),
    sa.Column('current_release_id', sa.String(length=128), nullable=True),
    sa.Column('owner_principal_id', sa.String(length=128), nullable=True),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace', 'asset_type', 'asset_key', name='uq_semantic_assets_namespace_type_key')
    )
    op.create_index('idx_semantic_assets_namespace_status_updated', 'semantic_assets', ['namespace', 'status', 'updated_at'], unique=False)
    op.create_index('idx_semantic_assets_type_status', 'semantic_assets', ['asset_type', 'status'], unique=False)
    op.create_table('semantic_asset_revisions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('asset_id', sa.String(length=128), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('revision_status', sa.String(length=32), nullable=False),
    sa.Column('spec_json', db_types.JsonType(), nullable=False),
    sa.Column('spec_checksum', sa.String(length=64), nullable=False),
    sa.Column('change_summary', sa.String(length=512), nullable=True),
    sa.Column('proposal_id', sa.String(length=128), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'revision_no', name='uq_semantic_asset_revisions_asset_revision_no')
    )
    op.create_index('idx_semantic_asset_revisions_asset_checksum', 'semantic_asset_revisions', ['asset_id', 'spec_checksum'], unique=False)
    op.create_index('idx_semantic_asset_revisions_status_created', 'semantic_asset_revisions', ['revision_status', 'created_at'], unique=False)
    op.create_table('semantic_asset_dependencies',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('asset_revision_id', sa.String(length=128), nullable=False),
    sa.Column('depends_on_asset_id', sa.String(length=128), nullable=False),
    sa.Column('depends_on_revision_id', sa.String(length=128), nullable=True),
    sa.Column('dependency_type', sa.String(length=64), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_semantic_asset_dependencies_depends_on', 'semantic_asset_dependencies', ['depends_on_asset_id', 'depends_on_revision_id'], unique=False)
    op.create_index('idx_semantic_asset_dependencies_revision', 'semantic_asset_dependencies', ['asset_revision_id'], unique=False)
    op.create_table('semantic_releases',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('release_no', sa.Integer(), nullable=False),
    sa.Column('namespace', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('scope_json', db_types.JsonType(), nullable=False),
    sa.Column('gate_result_json', db_types.JsonType(), nullable=False),
    sa.Column('previous_release_id', sa.String(length=128), nullable=True),
    sa.Column('rollback_of_release_id', sa.String(length=128), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('published_by', sa.String(length=128), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace', 'idempotency_key', name='uq_semantic_releases_namespace_idempotency_key'),
    sa.UniqueConstraint('namespace', 'release_no', name='uq_semantic_releases_namespace_release_no')
    )
    op.create_index('idx_semantic_releases_namespace_status_created', 'semantic_releases', ['namespace', 'status', 'created_at'], unique=False)
    op.create_table('semantic_release_assets',
    sa.Column('release_id', sa.String(length=128), nullable=False),
    sa.Column('asset_id', sa.String(length=128), nullable=False),
    sa.Column('revision_id', sa.String(length=128), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('asset_key', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('release_id', 'asset_id')
    )
    op.create_index('idx_semantic_release_assets_asset', 'semantic_release_assets', ['asset_id'], unique=False)
    op.create_index('idx_semantic_release_assets_revision', 'semantic_release_assets', ['revision_id'], unique=False)
    op.create_table('semantic_runtime_snapshots',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('release_id', sa.String(length=128), nullable=False),
    sa.Column('namespace', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('asset_manifest_json', db_types.JsonType(), nullable=False),
    sa.Column('binding_manifest_json', db_types.JsonType(), nullable=False),
    sa.Column('policy_manifest_json', db_types.JsonType(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_semantic_runtime_snapshots_namespace_status', 'semantic_runtime_snapshots', ['namespace', 'status'], unique=False)
    op.create_index('idx_semantic_runtime_snapshots_release', 'semantic_runtime_snapshots', ['release_id'], unique=False)
    op.create_index('uq_semantic_runtime_snapshots_active_namespace', 'semantic_runtime_snapshots', ['namespace'], unique=True, postgresql_where=sa.text("status = 'active'"), sqlite_where=sa.text("status = 'active'"))
    op.create_table('semantic_registry_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('object_name', sa.String(length=128), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('definition_hash', sa.String(length=128), nullable=True),
    sa.Column('last_loaded_at', sa.DateTime(), nullable=True),
    sa.Column('publish_status', sa.String(length=32), nullable=True),
    sa.Column('last_published_at', sa.DateTime(), nullable=True),
    sa.Column('last_drift_status', sa.String(length=32), nullable=True),
    sa.Column('last_drift_checked_at', sa.DateTime(), nullable=True),
    sa.Column('measure_summary_snapshot', db_types.JsonType(), nullable=True),
    sa.Column('certified_measure_list', db_types.JsonType(), nullable=True),
    sa.Column('lineage_summary', db_types.JsonType(), nullable=True),
    sa.Column('source_binding_summary', db_types.JsonType(), nullable=True),
    sa.Column('domain_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_type', 'object_name', name='uq_semantic_registry_object')
    )
    op.create_table('access_api_keys',
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('principal_id', sa.String(length=191), nullable=False),
    sa.Column('key_prefix', sa.String(length=128), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('scopes', db_types.JsonType(), nullable=False),
    sa.Column('allowed_ips', db_types.JsonType(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_rotated_at', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('created_by', sa.String(length=191), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['access_principals.principal_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key_id')
    )
    op.create_index('idx_access_api_keys_prefix', 'access_api_keys', ['key_prefix'], unique=False)
    op.create_index('idx_access_api_keys_principal', 'access_api_keys', ['principal_id'], unique=False)
    op.create_index('idx_access_api_keys_status', 'access_api_keys', ['status'], unique=False)
    op.create_table('access_principal_aliases',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('principal_id', sa.String(length=191), nullable=False),
    sa.Column('idp', sa.String(length=32), nullable=False),
    sa.Column('tenant_key', sa.String(length=128), nullable=False),
    sa.Column('external_id_type', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=191), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['access_principals.principal_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idp', 'tenant_key', 'external_id_type', 'external_id', name='uq_access_principal_alias_external')
    )
    op.create_index('idx_access_principal_aliases_principal', 'access_principal_aliases', ['principal_id'], unique=False)
    op.create_table('access_principal_preferences',
    sa.Column('principal_id', sa.String(length=191), nullable=False),
    sa.Column('theme', sa.String(length=16), server_default='system', nullable=False),
    sa.Column('default_landing', sa.String(length=128), server_default='/dashboard', nullable=False),
    sa.Column('list_page_size', sa.Integer(), server_default='20', nullable=False),
    sa.Column('table_density', sa.String(length=16), server_default='comfortable', nullable=False),
    sa.Column('extra', db_types.JsonType(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['access_principals.principal_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('principal_id')
    )
    op.create_table('access_service_principals',
    sa.Column('principal_id', sa.String(length=191), nullable=False),
    sa.Column('service_type', sa.String(length=32), nullable=False),
    sa.Column('owner_principal_id', sa.String(length=191), nullable=False),
    sa.Column('owner_team', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allowed_tenants', db_types.JsonType(), nullable=False),
    sa.Column('delegation_rules', db_types.JsonType(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.Column('disabled_by', sa.String(length=191), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_principal_id'], ['access_principals.principal_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['principal_id'], ['access_principals.principal_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('principal_id')
    )
    op.create_index('idx_access_service_principals_owner', 'access_service_principals', ['owner_principal_id'], unique=False)
    op.create_index('idx_access_service_principals_status', 'access_service_principals', ['status'], unique=False)
    op.create_index('idx_access_service_principals_type', 'access_service_principals', ['service_type'], unique=False)
    op.create_table('app_instances',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('app_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', db_types.JsonType(), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('schedule_config', db_types.JsonType(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_execution_at', sa.DateTime(), nullable=True),
    sa.Column('last_execution_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['app_code'], ['app_definitions.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dataset_code', sa.String(length=100), nullable=False),
    sa.Column('dataset_name', sa.String(length=200), nullable=False),
    sa.Column('dataset_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('physical_table', sa.String(length=200), nullable=True),
    sa.Column('sql_query', sa.Text(), nullable=True),
    sa.Column('file_metadata', db_types.JsonType(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=50), nullable=True),
    sa.Column('schema_snapshot', db_types.JsonType(), nullable=True),
    sa.Column('partition_fields', db_types.JsonType(), nullable=True),
    sa.Column('dimension_fields', db_types.JsonType(), nullable=True),
    sa.Column('metric_fields', db_types.JsonType(), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_code')
    )
    op.create_table('queries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('query_code', sa.String(length=100), nullable=False),
    sa.Column('query_name', sa.String(length=200), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('sql_query', sa.Text(), nullable=False),
    sa.Column('folder_id', sa.BigInteger(), nullable=True),
    sa.Column('tags', db_types.JsonType(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('execute_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_executed_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['query_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queries_created_by'), 'queries', ['created_by'], unique=False)
    op.create_index(op.f('ix_queries_folder_id'), 'queries', ['folder_id'], unique=False)
    op.create_index(op.f('ix_queries_is_favorite'), 'queries', ['is_favorite'], unique=False)
    op.create_index(op.f('ix_queries_is_template'), 'queries', ['is_template'], unique=False)
    op.create_index(op.f('ix_queries_query_code'), 'queries', ['query_code'], unique=True)
    op.create_index(op.f('ix_queries_source_id'), 'queries', ['source_id'], unique=False)
    op.create_table('query_execution_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('query_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=True),
    sa.Column('payload_json', db_types.JsonType(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['query_execution_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_query_execution_events_query_created', 'query_execution_events', ['query_id', 'created_at'], unique=False)
    op.create_table('query_result_objects',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('query_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('storage_type', sa.String(length=32), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=128), nullable=True),
    sa.Column('preview_json', db_types.JsonType(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ready_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['query_execution_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_id', name='uq_query_result_objects_query_id')
    )
    op.create_index('idx_query_result_objects_status_expires', 'query_result_objects', ['status', 'expires_at'], unique=False)
    op.create_table('scheduled_query_runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('query_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('rows_returned', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['scheduled_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_query_runs_query_id'), 'scheduled_query_runs', ['query_id'], unique=False)
    op.create_table('sql_queries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('sql', sa.Text(), nullable=False),
    sa.Column('limit_rows', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('result', db_types.JsonType(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_stack', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('job_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_executions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('instance_id', sa.BigInteger(), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('input_params', db_types.JsonType(), nullable=True),
    sa.Column('output', db_types.JsonType(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['app_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('dataset_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('context', db_types.JsonType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_fields',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dataset_id', sa.BigInteger(), nullable=True),
    sa.Column('physical_name', sa.String(length=100), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('is_nullable', sa.Boolean(), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('business_type', sa.String(length=20), nullable=True),
    sa.Column('sensitivity_level', sa.String(length=20), nullable=True),
    sa.Column('mask_rule', sa.String(length=50), nullable=True),
    sa.Column('field_tags', db_types.JsonType(), nullable=True),
    sa.Column('sample_values', db_types.JsonType(), nullable=True),
    sa.Column('field_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'physical_name', name='uk_dataset_field')
    )
    op.create_table('extraction_tasks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_name', sa.String(length=200), nullable=False),
    sa.Column('task_code', sa.String(length=100), nullable=True),
    sa.Column('dataset_id', sa.BigInteger(), nullable=True),
    sa.Column('query_id', sa.BigInteger(), nullable=True),
    sa.Column('select_fields', db_types.JsonType(), nullable=False),
    sa.Column('filter_conditions', db_types.JsonType(), nullable=False),
    sa.Column('sql_template', sa.Text(), nullable=True),
    sa.Column('row_limit', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.String(length=20), nullable=True),
    sa.Column('schedule_config', db_types.JsonType(), nullable=True),
    sa.Column('subscription_config', db_types.JsonType(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_code')
    )
    op.create_table('extraction_templates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('template_name', sa.String(length=200), nullable=False),
    sa.Column('dataset_id', sa.BigInteger(), nullable=True),
    sa.Column('select_fields', db_types.JsonType(), nullable=True),
    sa.Column('filter_template', db_types.JsonType(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('tags', db_types.JsonType(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_histories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('query_id', sa.BigInteger(), nullable=True),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('sql_query', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_rows', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_by', sa.String(length=100), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_histories_executed_at'), 'query_histories', ['executed_at'], unique=False)
    op.create_index(op.f('ix_query_histories_executed_by'), 'query_histories', ['executed_by'], unique=False)
    op.create_index(op.f('ix_query_histories_query_id'), 'query_histories', ['query_id'], unique=False)
    op.create_index(op.f('ix_query_histories_source_id'), 'query_histories', ['source_id'], unique=False)
    op.create_index(op.f('ix_query_histories_status'), 'query_histories', ['status'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('app_instance_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('event_types', db_types.ArrayOfString(), nullable=False),
    sa.Column('filter_conditions', db_types.JsonType(), nullable=True),
    sa.Column('delivery_config', db_types.JsonType(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_instance_id'], ['app_instances.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extraction_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=True),
    sa.Column('run_type', sa.String(length=20), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=True),
    sa.Column('execution_params', db_types.JsonType(), nullable=True),
    sa.Column('generated_sql', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('row_count', sa.BigInteger(), nullable=True),
    sa.Column('result_file_path', sa.Text(), nullable=True),
    sa.Column('result_size_mb', sa.Float(), nullable=True),
    sa.Column('delivery_method', sa.String(length=20), nullable=True),
    sa.Column('delivery_info', db_types.JsonType(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('download_url', sa.Text(), nullable=True),
    sa.Column('url_expires_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_stack', sa.Text(), nullable=True),
    sa.Column('notification_status', db_types.JsonType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['extraction_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('generated_sql', sa.Text(), nullable=True),
    sa.Column('query_result', db_types.JsonType(), nullable=True),
    sa.Column('visualization_config', db_types.JsonType(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_delivery_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('trigger_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sub_delivery_logs_subscription_id', 'subscription_delivery_logs', ['subscription_id'], unique=False)
    op.create_index('idx_sub_delivery_logs_trigger_at', 'subscription_delivery_logs', ['trigger_at'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sub_delivery_logs_trigger_at', table_name='subscription_delivery_logs')
    op.drop_index('idx_sub_delivery_logs_subscription_id', table_name='subscription_delivery_logs')
    op.drop_table('subscription_delivery_logs')
    op.drop_table('messages')
    op.drop_table('extraction_runs')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_query_histories_status'), table_name='query_histories')
    op.drop_index(op.f('ix_query_histories_source_id'), table_name='query_histories')
    op.drop_index(op.f('ix_query_histories_query_id'), table_name='query_histories')
    op.drop_index(op.f('ix_query_histories_executed_by'), table_name='query_histories')
    op.drop_index(op.f('ix_query_histories_executed_at'), table_name='query_histories')
    op.drop_table('query_histories')
    op.drop_table('extraction_templates')
    op.drop_table('extraction_tasks')
    op.drop_table('dataset_fields')
    op.drop_table('conversations')
    op.drop_table('app_executions')
    op.drop_table('sql_queries')
    op.drop_index(op.f('ix_scheduled_query_runs_query_id'), table_name='scheduled_query_runs')
    op.drop_table('scheduled_query_runs')
    op.drop_index('idx_query_result_objects_status_expires', table_name='query_result_objects')
    op.drop_table('query_result_objects')
    op.drop_index('idx_query_execution_events_query_created', table_name='query_execution_events')
    op.drop_table('query_execution_events')
    op.drop_index(op.f('ix_queries_source_id'), table_name='queries')
    op.drop_index(op.f('ix_queries_query_code'), table_name='queries')
    op.drop_index(op.f('ix_queries_is_template'), table_name='queries')
    op.drop_index(op.f('ix_queries_is_favorite'), table_name='queries')
    op.drop_index(op.f('ix_queries_folder_id'), table_name='queries')
    op.drop_index(op.f('ix_queries_created_by'), table_name='queries')
    op.drop_table('queries')
    op.drop_table('datasets')
    op.drop_table('app_instances')
    op.drop_index('idx_access_service_principals_type', table_name='access_service_principals')
    op.drop_index('idx_access_service_principals_status', table_name='access_service_principals')
    op.drop_index('idx_access_service_principals_owner', table_name='access_service_principals')
    op.drop_table('access_service_principals')
    op.drop_table('access_principal_preferences')
    op.drop_index('idx_access_principal_aliases_principal', table_name='access_principal_aliases')
    op.drop_table('access_principal_aliases')
    op.drop_index('idx_access_api_keys_status', table_name='access_api_keys')
    op.drop_index('idx_access_api_keys_principal', table_name='access_api_keys')
    op.drop_index('idx_access_api_keys_prefix', table_name='access_api_keys')
    op.drop_table('access_api_keys')
    op.drop_table('semantic_registry_entries')
    op.drop_index('uq_semantic_runtime_snapshots_active_namespace', table_name='semantic_runtime_snapshots')
    op.drop_index('idx_semantic_runtime_snapshots_release', table_name='semantic_runtime_snapshots')
    op.drop_index('idx_semantic_runtime_snapshots_namespace_status', table_name='semantic_runtime_snapshots')
    op.drop_table('semantic_runtime_snapshots')
    op.drop_index('idx_semantic_release_assets_revision', table_name='semantic_release_assets')
    op.drop_index('idx_semantic_release_assets_asset', table_name='semantic_release_assets')
    op.drop_table('semantic_release_assets')
    op.drop_index('idx_semantic_releases_namespace_status_created', table_name='semantic_releases')
    op.drop_table('semantic_releases')
    op.drop_index('idx_semantic_asset_dependencies_revision', table_name='semantic_asset_dependencies')
    op.drop_index('idx_semantic_asset_dependencies_depends_on', table_name='semantic_asset_dependencies')
    op.drop_table('semantic_asset_dependencies')
    op.drop_index('idx_semantic_asset_revisions_status_created', table_name='semantic_asset_revisions')
    op.drop_index('idx_semantic_asset_revisions_asset_checksum', table_name='semantic_asset_revisions')
    op.drop_table('semantic_asset_revisions')
    op.drop_index('idx_semantic_assets_type_status', table_name='semantic_assets')
    op.drop_index('idx_semantic_assets_namespace_status_updated', table_name='semantic_assets')
    op.drop_table('semantic_assets')
    op.drop_index('idx_semantic_modeling_proposals_status_updated', table_name='semantic_modeling_proposals')
    op.drop_table('semantic_modeling_proposals')
    op.drop_index('idx_semantic_modeling_sessions_status_updated', table_name='semantic_modeling_agent_sessions')
    op.drop_index('idx_semantic_modeling_sessions_principal_updated', table_name='semantic_modeling_agent_sessions')
    op.drop_table('semantic_modeling_agent_sessions')
    op.drop_index(op.f('ix_semantic_diagnose_runs_user_id'), table_name='semantic_diagnose_runs')
    op.drop_table('semantic_diagnose_runs')
    op.drop_table('scheduled_queries')
    op.drop_index(op.f('ix_query_templates_category'), table_name='query_templates')
    op.drop_table('query_templates')
    op.drop_index(op.f('ix_query_folders_parent_id'), table_name='query_folders')
    op.drop_index(op.f('ix_query_folders_created_by'), table_name='query_folders')
    op.drop_table('query_folders')
    op.drop_index('idx_query_exports_user_created', table_name='query_exports')
    op.drop_index('idx_query_exports_status_expires', table_name='query_exports')
    op.drop_index('idx_query_exports_status_created', table_name='query_exports')
    op.drop_table('query_exports')
    op.drop_index(op.f('ix_query_execution_jobs_trace_id'), table_name='query_execution_jobs')
    op.drop_index(op.f('ix_query_execution_jobs_status'), table_name='query_execution_jobs')
    op.drop_index(op.f('ix_query_execution_jobs_semantic_plan_id'), table_name='query_execution_jobs')
    op.drop_index(op.f('ix_query_execution_jobs_lease_expires_at'), table_name='query_execution_jobs')
    op.drop_index(op.f('ix_query_execution_jobs_engine_query_id'), table_name='query_execution_jobs')
    op.drop_index('idx_query_execution_jobs_status_lease_created', table_name='query_execution_jobs')
    op.drop_index('idx_query_execution_jobs_sql_hash', table_name='query_execution_jobs')
    op.drop_index('idx_query_execution_jobs_principal_created', table_name='query_execution_jobs')
    op.drop_table('query_execution_jobs')
    op.drop_index(op.f('ix_governance_audit_traces_timestamp'), table_name='governance_audit_traces')
    op.drop_index(op.f('ix_governance_audit_traces_target_type'), table_name='governance_audit_traces')
    op.drop_index(op.f('ix_governance_audit_traces_target_name'), table_name='governance_audit_traces')
    op.drop_index(op.f('ix_governance_audit_traces_sql_hash'), table_name='governance_audit_traces')
    op.drop_index(op.f('ix_governance_audit_traces_semantic_plan_id'), table_name='governance_audit_traces')
    op.drop_index(op.f('ix_governance_audit_traces_route_type'), table_name='governance_audit_traces')
    op.drop_index(op.f('ix_governance_audit_traces_principal_id'), table_name='governance_audit_traces')
    op.drop_index(op.f('ix_governance_audit_traces_maxcompute_task_id'), table_name='governance_audit_traces')
    op.drop_index(op.f('ix_governance_audit_traces_gateway_query_id'), table_name='governance_audit_traces')
    op.drop_index(op.f('ix_governance_audit_traces_decision'), table_name='governance_audit_traces')
    op.drop_table('governance_audit_traces')
    op.drop_table('feishu_chat_ref')
    op.drop_index('idx_domain_pub_records_published_at', table_name='domain_publish_records')
    op.drop_index('idx_domain_pub_records_domain_id', table_name='domain_publish_records')
    op.drop_table('domain_publish_records')
    op.drop_index('idx_datasource_table_cache_expires', table_name='datasource_table_cache')
    op.drop_index('idx_datasource_table_cache_datasource', table_name='datasource_table_cache')
    op.drop_table('datasource_table_cache')
    op.drop_table('data_sources')
    op.drop_table('channels')
    op.drop_table('app_definitions')
    op.drop_table('agent_query_log')
    op.drop_index('idx_access_role_bindings_subject', table_name='access_role_bindings')
    op.drop_index('idx_access_role_bindings_status', table_name='access_role_bindings')
    op.drop_index('idx_access_role_bindings_role', table_name='access_role_bindings')
    op.drop_table('access_role_bindings')
    op.drop_index('idx_access_principals_type', table_name='access_principals')
    op.drop_index('idx_access_principals_tenant', table_name='access_principals')
    op.drop_index('idx_access_principals_status', table_name='access_principals')
    op.drop_table('access_principals')
    op.drop_index('idx_access_policy_decisions_principal', table_name='access_policy_decisions')
    op.drop_index('idx_access_policy_decisions_level', table_name='access_policy_decisions')
    op.drop_index('idx_access_policy_decisions_decision', table_name='access_policy_decisions')
    op.drop_index('idx_access_policy_decisions_created', table_name='access_policy_decisions')
    op.drop_table('access_policy_decisions')
    op.drop_index('idx_access_execution_profiles_status', table_name='access_execution_profiles')
    op.drop_index('idx_access_execution_profiles_level', table_name='access_execution_profiles')
    op.drop_table('access_execution_profiles')
    op.drop_index('idx_access_delegation_events_message', table_name='access_delegation_events')
    op.drop_index('idx_access_delegation_events_delegated', table_name='access_delegation_events')
    op.drop_index('idx_access_delegation_events_created', table_name='access_delegation_events')
    op.drop_index('idx_access_delegation_events_actor', table_name='access_delegation_events')
    op.drop_table('access_delegation_events')
    op.drop_index('ix_access_data_policies_execution_profile_code', table_name='access_data_policies')
    op.drop_index('idx_access_data_policies_status', table_name='access_data_policies')
    op.drop_index('idx_access_data_policies_priority', table_name='access_data_policies')
    op.drop_table('access_data_policies')
    # ### end Alembic commands ###
