#!/usr/bin/env python3
# scripts/cutover/incident_init.py
# Round 4 · Sprint 0 · T-004c — 生成 incident Markdown（含飞书/协作 checklist；不调用飞书 OpenAPI，避免密钥进仓库）。

"""Create a structured incident document under docs/superpowers/ops/incidents/.

Usage:
  python3 scripts/cutover/incident_init.py "首页间歇 502"
  python3 scripts/cutover/incident_init.py --severity SEV2 "数据库迁移失败"

Does NOT create 飞书群 via API. The generated file contains a 飞书 section
with a placeholder link — create the group in Feishu/Lark and paste the URL.
"""

from __future__ import annotations

import argparse
import re
import textwrap
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
INC_DIR = REPO_ROOT / "docs" / "superpowers" / "ops" / "incidents"

SLUG_SAFE = re.compile(r"[^a-z0-9-]+")


def _slug(s: str) -> str:
    t = s.strip().lower().replace(" ", "-")
    t = SLUG_SAFE.sub("-", t)
    return re.sub(r"-+", "-", t).strip("-") or "incident"


def _build(
    title: str,
    severity: str,
    owner: str,
) -> tuple[str, Path]:
    ts = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M")
    slug = _slug(title)[:64]
    path = INC_DIR / f"{ts}-{slug}.md"
    when = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    body = f"""# Incident · {title}

- **id**: `{path.stem}`
- **opened**: {when}
- **severity**: {severity}  (SEV1=全站 | SEV2=多模块 | SEV3=单点)
- **owner**: {owner}
- **state**: open

## 1. 现象（What）

（客户/OnCall 可见症状：HTTP 码、时间窗、影响面）

## 2. 影响（Scope）

- 用户/租户：
- 数据完整性：

## 3. 飞书

> **本工具不自动建群**（避免 bot token 进入 CI/仓库）。请人工：
> 1. 在飞书创建「`INC-{ts}-{slug[:20]}`」群
> 2. 将群链接贴到下面一行

- **群链接（粘贴后删除本提示）**：
  - (pending)

**可选**：若本机已配置 `lark-cli` / OpenAPI，可在群内贴「Round 4 OnCall 手册」
`docs/superpowers/ops/round4-oncall-handbook.md` 供值班同学同步操作。

## 4. 时间线

| 时间(UTC) | 动作 |
| --- | --- |
| {when} | opened via `incident_init.py` |

## 5. 技术 checklist（T-004c）

- [ ] `scripts/cutover/health_probe.sh` 全绿 or 已定位红项
- [ ] `python3 scripts/cutover/digest_oncall.py` 已跑并附摘要
- [ ] backend / DB：`flask db current` 与 `upgrade head` 是否一致
- [ ] 若与发布相关：是否考虑 `deploy.sh --skip-migrate` 与 DBA 窗口
- [ ] 若需回滚：阅读 `scripts/cutover/rollback.sh` 头注释 **DEPRECATED**（D+14 后优先热修+forward fix）

## 6. 根因 & 复现

（RCA 草稿）

## 7. 修复 & 验证

- PR/Commit：
- 验证命令：

## 8. 收尾

- [ ] 对业务方/客户同步
- [ ] 关闭本 incident，链接 postmortem（若有）

---
*generated by `scripts/cutover/incident_init.py` (Round 4 T-004c)*
"""
    return textwrap.dedent(body), path


def main() -> int:
    ap = argparse.ArgumentParser(
        description="T-004c — create an incident markdown skeleton."
    )
    ap.add_argument("title", help="one-line title")
    ap.add_argument(
        "--severity", default="SEV2", help="SEV1 / SEV2 / SEV3 (default: SEV2)"
    )
    ap.add_argument(
        "--owner",
        default="oncall@unset",
        help="owner handle or email (default: oncall@unset — replace in file)",
    )
    ap.add_argument(
        "-n", "--dry-run", action="store_true", help="print path only, do not write"
    )
    args = ap.parse_args()

    text, path = _build(args.title, args.severity, args.owner)
    if args.dry_run:
        print(path)
        return 0
    INC_DIR.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
